### ISSUE TITLE
Examples not compiling

### ISSUE THREAD

**Issue by williamhdean** [asynclabs/WiShield_user_contrib#1]
Hi there.  Just downloaded your code and cant get the examples to compile.  I'm using the standard arduino java program.

for example on the WiFiScan, I get these errors when I compile:

error: expected constructor, destructor, or type conversion before '_' token In function 'void loop()':
 In function 'void printDesc(void_)':
 In function 'void udpapp_appcall()':
 In function 'void uip_dhcp_callback(const dhcp_state_)':
 In function 'void uip_dns_callback(char_, u16_t*)':

Is there something I should be doing differently in my environment?  (Windows with arduino)

**Comment by GregEigsti** [comment]
Please read/follow the instructions at the top of the WiFiScan sketch.  It builds just fine for me when I modify apps-conf.h per the instructions in the WiFiScan sketch.

**Comment by williamhdean** [comment]
That was it.  I read that before, but it didn't register.  Now I got it!!!!  Thank you!!!
